sudo: required
services:
  - docker

before_install:
  - docker build -t kartheekgopal/multi-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kartheekgopal/multi-test npm test -- --coverage

after_success:
  - docker build -t kartheekgopal/docker-multi-client ./client
  - docker build -t kartheekgopal/docker-multi-nginx ./nginx
  - docker build -t kartheekgopal/docker-multi-server ./server
  - docker build -t kartheekgopal/docker-multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push kartheekgopal/docker-multi-client
  - docker push kartheekgopal/docker-multi-nginx
  - docker push kartheekgopal/docker-multi-server
  - docker push kartheekgopal/docker-multi-worker